id: PCFF0E4D8
initial_creation_type: input
source_metadata:
  Title: Arya-samghata-sutra
  Editor: Oskar von Hinüber
  Publisher: Unpublished
  Place of Publication: '-'
  Year: '-'
  Āryasaṃghāṭa sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:59:28.023230'
last_modified_at: '2022-03-08T15:59:28.023240'
